spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: spectacles-service
          uri: lb://spectacles-service
          predicates:
            - Path=/spectacles/**
          filters:
            - RewritePath=/spectacles/(?<path>.*), /$\{path}
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
          filters:
            - RewritePath=/booking/(?<path>.*), /$\{path}
      discovery:
        locator:
          enabled: true

server:
  port: ${PORT:9000}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
