spring:
  application:
    name: api-gateway
server:
  port: ${PORT:9000}
zuul:
  routes:
    spectacles:
      path: /spectacles/**
      serviceId: spectacles-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
